"""
Mock vLLM Engine for local development without GPU.

Provides a simulated LLM engine for testing the API layer
when vLLM/CUDA is not available.
"""

from __future__ import annotations

import asyncio
import os
import random
from dataclasses import dataclass
from typing import AsyncIterator


@dataclass
class MockEngineConfig:
    """Configuration for the mock engine."""

    model_name: str
    simulated_delay: float  # Seconds per token

    @classmethod
    def from_env(cls) -> MockEngineConfig:
        """Load configuration from environment variables."""
        return cls(
            model_name=os.getenv("MODEL_NAME", "mock-model-v1"),
            simulated_delay=float(os.getenv("MOCK_DELAY_PER_TOKEN", "0.05")),
        )


@dataclass
class GenerationRequest:
    """Request for text generation."""

    request_id: str
    prompt: str
    max_tokens: int = 256
    temperature: float = 1.0
    top_p: float = 1.0
    stop: list[str] | None = None
    presence_penalty: float = 0.0
    frequency_penalty: float = 0.0
    n: int = 1
    logprobs: int | None = None
    echo: bool = False
    best_of: int = 1


@dataclass
class GenerationOutput:
    """Output from text generation."""

    request_id: str
    text: str
    prompt_tokens: int
    completion_tokens: int
    finish_reason: str | None
    logprobs: dict | None = None


# Sample responses for the mock engine
MOCK_RESPONSES = [
    "I'm a mock LLM running without GPU support. This is a simulated response for testing purposes.",
    "Hello! I'm the mock engine. In production, this would be powered by vLLM with actual model inference.",
    "This response is generated by the mock engine. It simulates LLM behavior for local development.",
    "Mock response: The quick brown fox jumps over the lazy dog. This tests the API pipeline.",
    "Testing 1, 2, 3... The mock engine is working correctly. No GPU required for this demo!",
]


class MockVLLMEngine:
    """Mock vLLM engine for development without GPU.

    Simulates the behavior of VLLMEngine for testing the API layer.
    """

    def __init__(self, config: MockEngineConfig | None = None) -> None:
        """Initialize the mock engine."""
        self.config = config or MockEngineConfig.from_env()
        self._started = False

    @property
    def model_name(self) -> str:
        """Get the model name."""
        return self.config.model_name

    async def start(self) -> None:
        """Simulate engine startup."""
        if self._started:
            return
        # Simulate model loading delay
        await asyncio.sleep(0.5)
        self._started = True

    async def stop(self) -> None:
        """Simulate engine shutdown."""
        self._started = False

    def is_ready(self) -> bool:
        """Check if engine is ready."""
        return self._started

    async def generate(self, request: GenerationRequest) -> GenerationOutput:
        """Generate a mock completion."""
        if not self.is_ready():
            raise RuntimeError("Engine not started")

        # Select a random response
        response_text = random.choice(MOCK_RESPONSES)

        # Truncate to max_tokens (rough approximation: 4 chars per token)
        max_chars = request.max_tokens * 4
        if len(response_text) > max_chars:
            response_text = response_text[:max_chars]

        # Simulate generation delay
        token_count = len(response_text) // 4
        await asyncio.sleep(token_count * self.config.simulated_delay)

        # Calculate token counts (approximation)
        prompt_tokens = len(request.prompt) // 4
        completion_tokens = token_count

        prefix = request.prompt if request.echo else ""

        return GenerationOutput(
            request_id=request.request_id,
            text=prefix + response_text,
            prompt_tokens=prompt_tokens,
            completion_tokens=completion_tokens,
            finish_reason="stop",
        )

    async def generate_stream(
        self, request: GenerationRequest
    ) -> AsyncIterator[GenerationOutput]:
        """Generate a streaming mock completion."""
        if not self.is_ready():
            raise RuntimeError("Engine not started")

        # Select a random response
        response_text = random.choice(MOCK_RESPONSES)

        # Echo prompt first if requested
        if request.echo:
            yield GenerationOutput(
                request_id=request.request_id,
                text=request.prompt,
                prompt_tokens=len(request.prompt) // 4,
                completion_tokens=0,
                finish_reason=None,
            )

        # Stream words one at a time
        words = response_text.split()
        prompt_tokens = len(request.prompt) // 4

        for i, word in enumerate(words):
            await asyncio.sleep(self.config.simulated_delay)

            # Add space before word (except first)
            text = f" {word}" if i > 0 else word
            is_last = i == len(words) - 1

            yield GenerationOutput(
                request_id=request.request_id,
                text=text,
                prompt_tokens=prompt_tokens,
                completion_tokens=i + 1,
                finish_reason="stop" if is_last else None,
            )

    async def abort_request(self, request_id: str) -> None:
        """Abort a request (no-op for mock)."""
        pass


# Global engine instance (singleton pattern)
_engine_instance: MockVLLMEngine | None = None
_engine_lock = asyncio.Lock()


async def get_engine() -> MockVLLMEngine:
    """Get or create the global engine instance."""
    global _engine_instance

    async with _engine_lock:
        if _engine_instance is None:
            _engine_instance = MockVLLMEngine()
        return _engine_instance


async def initialize_engine() -> MockVLLMEngine:
    """Initialize and start the global engine."""
    engine = await get_engine()
    await engine.start()
    return engine


async def shutdown_engine() -> None:
    """Shutdown the global engine."""
    global _engine_instance

    async with _engine_lock:
        if _engine_instance is not None:
            await _engine_instance.stop()
            _engine_instance = None
